### ISSUE TITLE
Can the filehub run 'syncthing'?

### ISSUE THREAD

**Issue by wtanksleyjr** [digidem/filehub-config#1]
I used to carry a little cluster of gadgets to keep my data synced; this would replace them all, except that I've now added 'syncthing' to my mix (it performs secure data synchronization between multiple systems).

Would there be any chance of getting that into this mix?

**Comment by gmaclennan** [comment]
The filehub device has really limited memory and resources, so I think this would be really hard. You would also need to compile syncthing for the device using [OpenWRT Buildroot](http://downloads.openwrt.org/docs/buildroot-documentation.html). This is what I did to get rsync working, but I had to store the binary on the external drive because there is not enough room on the filehub, and I needed to create a swapfile since memory on the device is limited. I would think that it's too much work, and likely would not work. You would be better compiling similar scripts to these on a Raspberry Pi and using that.
